### ISSUE TITLE
Add link to javadoc

### ISSUE THREAD

**Issue by danny-larsen** [auth0/java-jwt#107]
Might be a good idea to put a link to the java doc somewhere on the readme page? Took me some time to find it: https://www.javadoc.io/doc/com.auth0/java-jwt/2.2.1

**Comment by lbalmaceda** [comment]
Hi @danny-larsen. 
The javadoc it's bundled into every release so the IDE can display it when you require the dependency.

**Comment by djensen47** [comment]
First just wanted to say that this is a great library. Thanks for all the hard work on it.

Just wanted to propose that this issue be reconsidered. Since we're not always in an IDE or an IDE that supports Javadoc, having a link to the javadoc (https://www.javadoc.io/doc/com.auth0/java-jwt/) on the README is super useful.

**Comment by lbalmaceda** [comment]
@djensen47 Thanks for reaching out! Adding the link to the readme is something we can totally do. Let me re-open this.
