### ISSUE TITLE
Cannot add map objects to claims

### ISSUE THREAD

**Issue by davide-maestroni** [auth0/java-jwt#135]
I have troubles migrating from version 2 to version 3 of the library. In particular, there seems to be no way to generate a signature for an object like the one described [here](https://auth0.com/docs/api/management/v2), since the "scopes" claim is a map of objects. The `withClaim()` methods support only basic types and arrays of strings and integers, but I believe several more types (like maps) should be supported as well. Why not just exposing a method `withClaim(String name, Object value)`?

**Comment by hzalaz** [comment]
@davide-maestroni we thought about that and we decided to keep the types of the claims simple since the jwt structure should be very simple and the bigger the object graph you have the bigger the token is. 
Also there is no way for us to ensure that the POJO can be serialized to JSON, we need to leverage that to the library user.

About the scopes for api v2, you can also use `scope` instead of `scopes` and each scope space separated with the following format `entity:action`.

Will evaluate later how we can add some support for Maps at least

**Comment by davide-maestroni** [comment]
@hzalaz Ok, I see your point, I'll go for the `scope` version then. Thank you for the quick reply.

**Comment by kwkhaw** [comment]
@davide-maestroni same here. We need a way to add Map to the claims.
