### ISSUE TITLE
How to generate public and private key?

### ISSUE THREAD

**Issue by NE-SmallTown** [auth0/java-jwt#148]
Hi.I notice that the [test file](https://github.com/auth0/java-jwt/blob/c07116eda79059c421794b85c148f7538421b318/lib/src/test/java/com/auth0/jwt/algorithms/RSAAlgorithmTest.java#L40) use `readPublicKeyFromFile` and  `readPublicKeyFromFile` use `parsePEMFile`,but there is no doc about the `parsePEMFile`.

The `parsePEMFile` method use `PemReader` to read the key from file,but the question is **at the first time there is no file such as `src/test/resources/rsa-public.pem`**.I check the the [src code](https://github.com/auth0/java-jwt/blob/c07116eda79059c421794b85c148f7538421b318/lib/src/test/java/com/auth0/jwt/PemUtils.java#L21),but I don't understand why throw a error rather than **create the key pair and create the file and put the key pair into it**.

So I don't know how [the getPublicKey method](https://github.com/auth0/java-jwt/blob/c07116eda79059c421794b85c148f7538421b318/lib/src/test/java/com/auth0/jwt/PemUtils.java#L28) generate the public and private key.

According to current java-jwt api,we must create the public and privte key files before we use the api,it's  a little inconvenient.

On the other hand,I don't use jsp or spring or spring mvc.I just use struts2 for the json api.

Final question,when we create the token,we use `JWT.create().withIssuedAt(date) ` and here the `date` is type of `Date`,but I find that when we vertify the token,the [verifyClaims method](https://github.com/auth0/java-jwt/blob/1a959950d56758b9f001e076020626a0357b0f24/lib/src/main/java/com/auth0/jwt/JWTVerifier.java#L369) convert `Date` to `Long`?I test `(Long)(new Date())`,it will throw error,but the verifyClaims method won't,so I want to how it works?

Could any one help me?.Thanks a lot.

**Comment by lbalmaceda** [comment]
Hi @NE-SmallTown,
The [PemUtils](https://github.com/auth0/java-jwt/blob/master/lib/src/test/java/com/auth0/jwt/PemUtils.java) class is inside the `test` package because it's only used for testing. In the tests, we provide both secrets or [certificates](https://github.com/auth0/java-jwt/tree/master/lib/src/test/resources) and the already signed token. The library itself doesn't have any method to generate the key pair, that's up to you. 

Regarding the dates, the [RFC](https://tools.ietf.org/html/rfc7519#page-6) tells every date/time value must be converted to a `NumericDate` format. That's epoch time (seconds): We convert the date [to seconds](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/impl/PayloadSerializer.java#L58) when we write the json. Then on the decode, we convert the seconds back [to date](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/impl/PayloadDeserializer.java#L71).

Cheers,

**Comment by NE-SmallTown** [comment]
Thanks for your clarification.
