### ISSUE TITLE
RSA JWT verification example mentions private key

### ISSUE THREAD

**Issue by advoretsky** [auth0/java-jwt#189]
usage of the private key in the 'verification' example is confusing:
```
Algorithm algorithm = Algorithm.RSA256(publicKey, privateKey);
JWTVerifier verifier = JWT.require(algorithm)
```

**Comment by lbalmaceda** [comment]
That's because the `Algorithm` instance is reusable and works for JWT creation as well. The 'signing' sample has the same _problem_. The readme is meant to be read in order.. You can ignore one of the keys (null) as long as the other is valid. This is explained [here](https://github.com/auth0/java-jwt#pick-the-algorithm).
