### ISSUE TITLE
java.lang.NoSuchMethodError: com.auth0.jwt.JWT.decode(Ljava/lang/String;)Lcom/auth0/jwt/JWT;

### ISSUE THREAD

**Issue by acaaad** [auth0/java-jwt#197]
I'm trying to decode my JWT using this code:
```
  private static DecodedJWT decodeJWT(String token) {
    return JWT.decode(token);
  }
```

and getting these error:
```
...
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.auth0.jwt.JWT.decode(Ljava/lang/String;)Lcom/auth0/jwt/JWT;
...
```

I'm using Java JWT 3.2.0. Please Advice

**Comment by lbalmaceda** [comment]
I can't reproduce it. Any other info you can provide?

**Comment by oktaviandi-nugraha** [comment]
Hi @lbalmaceda,

I'll provide the context of what actually happened. I provide a library that depends to java-jwt version 3.1.0. Let's call this auth library.

@acaaad in his build.gradle, declared a dependency to my auth library. Somewhere in his repo, there's another module that depends to java.jwt version 3.2.0. Thus, the java.jwt library loaded at runtime is 3.2.0. 

In my library I call this method:

com.auth0.jwt.JWT.decode(token)

In version 3.1.0, this method returns a JWT class that implements DecodedJWT interface. But, in version 3.2.0, JWT class doesn't implement DecodedJWT. The above method returns DecodedJWT.

Thus, at runtime we got the above error because JWT.decode doesn't return JWT anymore.

Question is @lbalmaceda, is there any reason why JWT doesn't implement DecodedJWT interface anymore? In this case it's not backward compatible. If you guys are using semantic versioning, minor increment should preserve backward compatibility.

**Comment by jspetrak** [comment]
Reading the commit: https://github.com/auth0/java-jwt/commit/72bceb977586a1736035ccc74220d14bc466f0c4#diff-8ad89ade07b642e1a02866acf5562b86
the intent was probably to make the JWT class the central utility object for JWT library.

**Comment by jspetrak** [comment]
@oktaviandi-nugraha Do you have any example of a library dependend on java-jwt:3.1.0?

**Comment by oktaviandi-nugraha** [comment]
@jspetrak My library is an internal library at work.

**Comment by lbalmaceda** [comment]
@oktaviandi-nugraha @acaaad Ok that makes more sense. We changed it [here](https://github.com/auth0/java-jwt/pull/167#issue-223188921) to avoid confusion. As @jspetrak said we wanted to have a single entry point (the JWT class) with a different output class. Although it's true this is breaking, it's not as breaking as removing methods or changing behavior. It's fixed by just by changing the returned class from JWT to DecodedJWT like the PR says, the rest remains the same. So your options here are:
- Make both libraries use the same version of `java-jwt`. (honestly, it shouldn't take more than 2 mins to update your "auth library")
- Request `java-jwt 3.2.0` in the library and exclude the `java-jwt 3.1.0` required by your "auth library" dependency, using some of the techniques explained in [gradle docs](https://docs.gradle.org/current/userguide/dependency_management.html#sub:exclude_transitive_dependencies).
Apologies for the confusion.

**Comment by acaaad** [comment]
Hi @jspetrak @lbalmaceda thank you for your answer. 
We finally made it work by making this authentication library depends on java-jwt version 3.2.0

Will close this issue now.
