### ISSUE TITLE
[PATCH] JWTVerifier: allow verify parsed tokens

### ISSUE THREAD

**Issue by jcodagnone** [auth0/java-jwt#208]
Today you can't parse the token once and verify it against N validators
(based on the algorithm or another feature…).

Decoding the token is not cheap in general terms (there are lots of
strings instantiations)

[0001-JWTVerifier-allow-verify-parsed-tokens.txt](https://github.com/auth0/java-jwt/files/1400032/0001-JWTVerifier-allow-verify-parsed-tokens.txt)

**Comment by kaandok** [comment]
@lbalmaceda hi, any plans to merge this in/any help required?

**Comment by filip26** [comment]
note this patch is workaround for #246 because allows to have multiple different verifiers.

e.g.
1. decode token
2. use decoded token property (e.g. issuer) to select appropriate verifier
3. call verifier.verify(decoded token)

**Comment by rocketraman** [comment]
I created a custom validator that can be used effectively for this and other use cases: https://github.com/auth0/java-jwt/pull/290

**Comment by rocketraman** [comment]
@AndreasHuber-CH Replying to your comment here:

> Hi. This looks nice, but it doesn't cover #208 entirely. For example it is still not possible to chose the algorithm based on the JWT header.

Yes, the algorithm is the special case because passing it is right now seems to be the only way to obtain a `Verification`. Note that I believe it was done this way to avoid a security risk -- if you chose the algorithm based on the token itself, then you are opening yourself up to a "none" algorithm: see https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/.

**Comment by lbalmaceda** [comment]
Was added here https://github.com/auth0/java-jwt/issues/279
