### ISSUE TITLE
Add support for RSA-PSS (PS256) family

### ISSUE THREAD

**Issue by ecki** [auth0/java-jwt#225]
The RSA PSS variant of signatures (PS256, ...) is not supported for verification. Since the PKCS1.5 padding is regarded as risky and outdated it would be a good idea to support the new scheme as well. (currently planning to provide a PR)

**Comment by ecki** [comment]
This is my first draft. It does not yet testing, since test vectors are not present it might not be compliant. This requires a JCE provider which does support PSS (like BouncyCastle). Not so happy about introducing the paramSpec in Algorithm, maybe change the layout to initialise with a initialized Signature?

https://github.com/auth0/java-jwt/compare/master...ecki:feature-rsapss?expand=1

**Comment by DinoChiesa** [comment]
Any update on this?

**Comment by lbalmaceda** [comment]
> This requires a JCE provider which does support PSS (like BouncyCastle)

So users would be required to add this provider to the classpath and we would need to check its presence on runtime.. I can't imagine that looking good on the code 💃 but I'll think about it. This is not a priority though, so I'll keep it open until we decide to work on PSS.

**Comment by ecki** [comment]
Received the Staleness reminder, in the meantime RSAPSS landed in JCE 11, maybe this makes the implementation more feasible (nimbus seems to implement it)

**Comment by lbalmaceda** [comment]
This is not in our backlog so I'm tagging it as a feature request in case anyone wants to help provide a PR. 

I suggest the implementation considers the scenario where a security provider is not passed and defaults to the Java one. Eventually, any security provider must be optional in the sense that the user must explicitly require the external dependency if they want to use that specific provider, and not be forced to require it just because of using this library with the default behavior.

**Comment by lbalmaceda** [comment]
This has been open for a long time now. We've evaluated it with the team and decided to not move forward with this request, as it's not something we plan to support in the short/mid-term.
