### ISSUE TITLE
Is there any way to put object data in claim?

### ISSUE THREAD

**Issue by AlexC-developer** [auth0/java-jwt#247]
I want to put an object data in the claim...lol

**Comment by ph-kaelin** [comment]
we also want to put objects data (nested json) as claim.
Looks like this is common practise for the address.
{
  "sub": "...",
  "address": {
    "street_address": "...",
    "locality": "...",
    "region": "...",
    "postal_code": "...",
    "country": "..."
  },
  "locale": "..."
}

This library seems to be able to do that:   maven: com.inversoft / prime-jwt / 1.1.0

**Comment by viksrastogi** [comment]
Please provide this feature. I also need Object data to be passed as claim in one of my projects.

**Comment by sirpoisonivy** [comment]
Agree. Would be nice to have.

**Comment by AlexandreOlipe** [comment]
I've read some discussions  about this and none had a "happy ending" since this feature seems controversal(#163, #164, #204, #227, etc). I only like to know why this is not supported and controversal since we have something similar in  ".withHeader(Map<String, Object> headerClaims)".
Are there other reasons to not implement the same concept to load a simple map in payload?
I ask that because I need to provide some permissions in payload (a very few data to use in an app). Something like this:
```
{
  "perm": {
    "person": ["picture", "address"],
    "vehicle": ["debits"]
  }
}
```
But it is allowed only to do something like this:
```
{
  "perm": [
    "person",
    "vehicle"
  ]
}
```

This is an artifice I use to ensure that I can hide some elements in the app interface (only showing the default components and the restricted components listed in "perm").
What is wrong in that? There is some other way to provide this informatio whitout custom object serialization in a string (this is a very bad way to achieve this behavior, IMO).

If there's a way we can help, please let us know too. I just don't want to need switching JWT library nor create my own sollution, since this seems like needed by several users.

Thank you all.

**Comment by sirpoisonivy** [comment]
Totally agree. The author has stipulated he will approve a simple solution to support a Map implementation which supports only the primative types. I need to write that, it's super simple.

**Comment by AlexandreOlipe** [comment]
I can be very wrong... But watching the discussions, I think that anything like: 

`.withMapClaim(String name, Map<String, Object> items)`
or
`.withMapClaim(String name, Map<String, Set<String>> items)`
or
`.withMapClaim(String name, Map<String, List<String>> items) `

Would make almost everybody happy (since, generaly, the needs are for very simple maps). In my case, any of these would do the magic :)

Just to remember: The first case (with Map<String, Object>) already exists in ".withHeader(Map<String, Object> headerClaims)" solution. So I believe that there is no need to implement a whole new algorithm.

**Comment by sirpoisonivy** [comment]
I think it was left in that unfinished state to avoid errors when attempting to serialize custom objects. The header likewise needs similar enforcement. I'll write it if someone doesn't get to it before me. Just needs put methods with all the primative wrappers.

**Comment by TheLuminary** [comment]
I find that it is bizarre that there is an `asMap()` method on the Decoder, but no way to get this information into the token with the creator.

**Comment by AlexC-developer** [comment]
@TheLuminary Thanks bro , but I no longer need this feature.

**Comment by TheLuminary** [comment]
@AlexC-developer Fair enough.

For anyone else that might arrive here from Google. I was able to work around this, by just wrapping the creator and decoder. And implementing the asMap that I wanted, by using a String Array, with the array values using the {Key}_{Value} pattern. This is not perfect, but it allows me to cleanly encode a String,String map which is what my use case was.

**Comment by lbalmaceda** [comment]
I plan to open the JSON encoding/decoding module so that anyone can plug in their library. This is the first step to achieve the issue described in this post successfully. Just a heads up, as I can't promise any ETA unfortunately.

**Comment by StephenOTT** [comment]
+1, just ability to access nested claims!

**Comment by pavankumarjs** [comment]
@lbalmaceda checking whether we can plugin the JSON encoding/decoding?

**Comment by lbalmaceda** [comment]
@pavankumarjs not yet. This is an item on our backlog 👍
