### ISSUE TITLE
LocalDate/LocalDateTime support 

### ISSUE THREAD

**Issue by mrvonwyl** [auth0/java-jwt#250]
First of all thanks for this awesome piece of software!

However, I would like to be able to use the Java 8 time API for all the timestamps.
Since I am using LocalDate and LocalDateTime everywhere else, it would be nice, if I would not need to convert the values to the old java.util.Date. Especially in the for JWT.create() and JWT.require() methods.

Thanks :)

**Comment by lbalmaceda** [comment]
Hi 👋 Even if we could add a method that accepts that new type, this library's min JDK is 1.7. I know that converting it is a valid solution but one we don't really like at all as it's not performant, and we're already doing text-to-value conversions when dealing with the tokens. Do you think there's any workaround?
This is definitely a must have in the case of a new major.

**Comment by Clockwork-Muse** [comment]
Side note: `LocalDate`/`LocalDateTime` aren't the correct types here.  For the various registered claims, the correct type should be `Instant`.  Either of the `Local..`s attach presumed data to the token (that is, a time zone) which doesn't actually exist.

Not that there couldn't be private claims that would be `LocalDate` (say, birthday), but the parser would have to take `java.util.time.Clock` (which it would have to anyways, if `Instant` is in use), and possibly be able to use a timezone from another claim (since there's a minimum of two calendar days being observed at once, sometimes three).

**Comment by medmoufahim** [comment]
@mrvonwyl : What solution did you choose for using the java 8 time API for setting dates in JWT claims ?

poke @lbalmaceda @Clockwork-Muse thanks

**Comment by mrvonwyl** [comment]
@medmoufahim I am not working on that project anymore, so I am not sure if this answer is still valid.
I was feeding the JWT API with java.util.Date objects, since there was no other solution. However I converted them from and to LocalDateTime. This works for me, since the app only runs in one timezone.

**Comment by RockyMM** [comment]
`java.util.Date` and `java.time.Instant` are more or less interchangeable, yet `java.time.Instant` has a lot of benefits compared to the old `Date`. 

As most of the Java landscape is on Java 8 for a long time now, I think it's an excellent idea to include `Instant` instead of `Date`. From a performance standpoint, `Instant` should be very close to `Date` so there is little to no risk there.

**Comment by glorat** [comment]
Workaround should be to use use `java.util.Date.from(instant)` to pass in instants. Using LocalDateTime or LocalDate can get you into timezone trouble as has already been pointed out

**Comment by jimmyjames** [comment]
Version 4 will support `Instant`-based DateTime claims, as added in https://github.com/auth0/java-jwt/pull/392

**Comment by Tony308** [comment]
The post only talked about claims but concerning `nbf, iat and exp`, would `Instant` still be the correct solution instead of possibly supporting LocalDate/LocalDateTime?
