### ISSUE TITLE
Support JWT verification with just a public key

### ISSUE THREAD

**Issue by pjfanning** [auth0/java-jwt#252]
I'm using an Auth0 domain and have a [JWK](https://github.com/auth0/jwks-rsa-java/blob/master/src/main/java/com/auth0/jwk/Jwk.java). This only exposes a PublicKey.
https://github.com/auth0/java-jwt#verify-a-token RS256 example requires that you provide a PublicKey and a PrivateKey.
Verification of a JWT only requires the PublicKey and I don't have access to the PrivateKey.

I will try https://github.com/jwtk/jjwt for the JWT verification but it would be nice not to mix and match various libraries.

**Comment by pjfanning** [comment]
I was able to get this to work with a custom RSAKeyProvider as follows:

```
  val provider = new GuavaCachedJwkProvider(new UrlJwkProvider(domain))
  val keyProvider = new RSAKeyProvider() {
    override def getPublicKeyById(kid: String): RSAPublicKey = {
      val jwk = provider.get(kid)
      jwk.getPublicKey.asInstanceOf[RSAPublicKey]
    }
    override def getPrivateKey: RSAPrivateKey = null
    override def getPrivateKeyId: String = null
  }

  val algorithm = Algorithm.RSA256(keyProvider)
  JWT.require(algorithm).build().verify(holder.getIdToken)
```

**Comment by lbalmaceda** [comment]
An `Algorithm` instance requires that you provide [at least one](https://github.com/auth0/java-jwt#pick-the-algorithm) key (public/private). By using the `KeyProvider` interface (or it's implementations) you can pass that public key you need for verification, just [like you did](https://github.com/auth0/java-jwt#using-a-keyprovider) in your snippet. All this is already explained in the readme. 


> would be nice not to mix and match various libraries.

Handling keys is **not** part of this library. We don't create nor read keys. In fact, this library makes use of the `PublicKey` and `PrivateKey` interfaces so you use whatever method you want to obtain them. That also includes reading it from a JWKs file, which we know is a common scenario and that's why we provide it in a small separate library (also pointed by the readme).

Cheers
