### ISSUE TITLE
java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/auth0/jwt/algorithms/Algorithm

### ISSUE THREAD

**Issue by hariprasath-r** [auth0/java-jwt#269]
I want to generate JWT Token using RSA Key pairs in Java 6. But the Algorithm class is not supporting it. Can someone let me know which version of jar to use for the above case.

Thanks in advance.

**Comment by lbalmaceda** [comment]
This library's minimum supported Java version is JDK 7. In fact, the [StandardCharsets](https://docs.oracle.com/javase/7/docs/api/java/nio/charset/StandardCharsets.html) class is available since 1.7. Look at https://github.com/auth0/java-jwt/blob/master/lib/build.gradle#L32-L33. 

I'll add this requirement to the readme for better visibility, and leave this issue open for a while so others can help you get another answer.
