### ISSUE TITLE
Expose new new verify method signature.

### ISSUE THREAD

**Issue by KowalczykBartek** [auth0/java-jwt#279]
Hi Auth0 team :) 
recently I found that it would be quite useful to have following method signature,
```java
public DecodedJWT verify(DecodedJWT decodedJWT)
```
I have use case for first, checking some stuff inside JWT token, then, in some cases I want to check signature - to not waste CPU cycles, it would be good to have verify method that accepts DecodedJWT instance.

Pull request with change is here : https://github.com/auth0/java-jwt/pull/280

Thanks !

**Comment by martinoconnor** [comment]
This is useful when using JWKS but not `KeyProvider`. Unfortunately `KeyProvider` provides no means for dealing with exceptions that may occur when retrieving the key.

**Comment by rocketraman** [comment]
How about using this custom validator I just created? https://github.com/auth0/java-jwt/pull/290

**Comment by KowalczykBartek** [comment]
From my perspective, it would be simpler to just call method that already is there :)

**Comment by martinoconnor** [comment]
@rocketraman a new custom validation would not solve the case where we need to read the contents of the JWT before we can verify it. This issue makes sense because we would not have to parse the JWT a second time.

**Comment by martinoconnor** [comment]
@rocketraman no, sometimes you have to decode the JWT before you can verify it. If it is signed with the RS246 algorithm and the public key is available via JWKS, it is necessary to decode the JWT to retrieve the key ID so the public key can be looked up in the providers' well-known location for publishing JWKS public keys.

**Comment by rocketraman** [comment]
@martinoconnor  Yes, but that is what the `KeyProvider` is for. I just used this myself to validate tokens from Microsoft Azure AD. That is acceptable because its a limited purpose hook, not a general "give me everything and let me decide what to do".

**Comment by KowalczykBartek** [comment]
guys - @martinoconnor , @rocketraman - are you sure that someone still maintains that project ? XD

**Comment by martinoconnor** [comment]
@rocketraman 
1. This PR is not for allowing the JWT to be decoded without verification, that functionality has long existed. This PR allows a previously decoded JWT to subsequently be verified. You should probably actually look at the PR source
2. The `KeyProvider` does not currently handle exceptions very well, for example, if there are network issues while accessing the JWKS, there is not really a good way to handle it yet

@KowalczykBartek I think @lbalmaceda maintains this project

**Comment by rocketraman** [comment]
> 1. This PR is not for allowing the JWT to be decoded without verification, that functionality has long existed. This PR allows a previously decoded JWT to subsequently be verified. You should probably actually look at the PR source

Fair enough. Though note the statement in the docs: "Use it only if you trust the token or you already verified it." I'll leave it at that -- this is all mostly O/T anyway.

> 2\. The `KeyProvider` does not currently handle exceptions very well, for example, if there are network issues while accessing the JWKS, there is not really a good way to handle it yet

With appropriate caching this should happen quite rarely. Why not just throw a specialized `JWTVerificationException`? It's likely you'll need to treat this the same way as an invalid JWT anyway, and if not you can always catch your specialized exception and do something else.

**Comment by lbalmaceda** [comment]
>Yes, but that is what the KeyProvider is for.

I agree with @rocketraman here. 

@KowalczykBartek @martinoconnor wouldn't it be better if the `KeyProvider` is refactored, so that it now throws an unchecked exception that the `Algorithm` can handle and wrap into `SignatureVerificationException`? Note as @rocketraman mentions above, not being able to obtain the key (for whatever reason) would mean the signature won't be able to be verified so that's a fail scenario as well. How would you expect the library to behave in such a case?

**Comment by KowalczykBartek** [comment]
@lbalmaceda honestly I am out of discussion at the moment, it somehow changed direction :) I just wanted to have method that will do some specific stuff according to existing logic.

>  How would you expect the library to behave in such a case?

I expect that nothing change :)

**Comment by kibear** [comment]
It just verify a string token or a object token, just it. Not trust token, as you mind, verify the string token you have trusted the string token, so object token with string token has any difference.

**Comment by lbalmaceda** [comment]
The problem with allowing people to just decode the token without a following verification is that they might start to use the token claims as trusted data immediately after they decode it. And that's an error: **No data should not be trusted at all until the token's signature is verified**. _You_ might know the risks and would try to decode it and if required, verify the signature yourself. But most of the users don't know or don't read those warnings; I rather have a library that can protect those users from misuse than having to open the API in the other direction. For the next major I plan to have something like this that allows users to check existence of claims but not obtain its value until the token is verified. Doing this today would be a breaking change since methods signature would change.

The only use case this library and the spec that it tries to implement support is using the key id claim to fetch the proper JWK on demand (RS algorithms). That's what the `KeyProvider` interface is here for, and I'm willing to refactor it as much as required to fix whatever mistakes you find on its implementation.

**Comment by rcollette** [comment]
Was an architectural decision just made based on the presumption the user base being incompetent rather than an expressed use case?

**Comment by kibear** [comment]
`
public DecodedJWT verify(String token) throws JWTVerificationException {

        DecodedJWT jwt = JWT.decode(token);
        verifyAlgorithm(jwt, algorithm);
        algorithm.verify(jwt);
        verifyClaims(jwt, claims);
        return jwt;
    }
`
just call this line DecodedJWT jwt = JWT.decode(token); by myself, why cannot? It's not influence the verify logic.
In java world, every thing is object, so verify a DecodedJWT object is a right way, not a plain string token. Even the string token verify method, the code also decode string to an DecodedJWT object first, then verify the DecodedJWT object, It just move decode method by my hand, it cannot , it's very funny！

**Comment by martinoconnor** [comment]
@lbalmaceda looks like the OP got frustrated and decided to leave. Can we reopen this issue to keep the conversation going here?
