### ISSUE TITLE
Cannot use header claim "typ" if I want to sign the token

### ISSUE THREAD

**Issue by agrajm** [auth0/java-jwt#298]
When I try to use both `typ` header claim 
```
Map<String, Object> headerClaims = new HashMap<>();
headerClaims.put("typ", "MyToken");
jws = JWT.create()
          .withHeader(headerClaims)
          ....
```
and sign the token using 
```
jws = JWT.create()
          .withHeader(headerClaims)
          ...
          .withExpiresAt(expiryDate)
          .withNotBefore(notBeforeDate)
          .withIssuedAt(currentDate)
          .sign(Algorithm.HMAC256("some-secret"));
```
the sign implementation always overrides the header set using `headerClaims` due to the code [here](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/JWTCreator.java#L306) - its always hardcoded to `JWT` 
Can we please look in the header claims before hardcoding this value or give an alternate way to define our own value for `typ` header claim and sign the token as well ?

**Comment by lbalmaceda** [comment]
It is hardcoded because that value was [recommended](https://tools.ietf.org/html/rfc7519#section-5.1) by the RFC that this SDK attempts to follow. While _recommended_ is not a _must_, the SDK today doesn't allow you to override it, as you mentioned. This SDK focuses on the JWT RFC linked above and **does not support JWS nor JWE**, so knowing in advance that I can ensure that the `typ` of the tokens created by this library will always be "JWT".

What do you want to send there and why? Remember those `typ` values must conform to [this list](https://tools.ietf.org/html/rfc7515#ref-IANA.MediaTypes).

**Comment by agrajm** [comment]
Hi @lbalmaceda thanks for replying. 
The reason I'm trying to send something else in the `typ` header claim is because the third party API I need to call, requires it that way :( 
Thanks for clarifying - I tried using https://github.com/jwtk/jjwt and it seems like it allows me to put any random stuff I want in the header claim

**Comment by lbalmaceda** [comment]
Ok. I'll close this now.
