### ISSUE TITLE
Use java.util.Base64 instead of apache commons-codec

### ISSUE THREAD

**Issue by quaff** [auth0/java-jwt#302]

**Comment by KowalczykBartek** [comment]
Hi, 
any plans to do that?

**Comment by KowalczykBartek** [comment]
Thank you :)

**Comment by nightowlengineer** [comment]
Pinging to avoid closure

**Comment by danielfaust** [comment]
I have an Android app here. When calling `JWT.decode(tokenResult.getToken()).getSignature()` on Android 10, it works fine. But on Android Pie 9.0 I get

```
java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
        at com.auth0.jwt.JWTDecoder.<init>(JWTDecoder.java:35)
        at com.auth0.jwt.JWTDecoder.<init>(JWTDecoder.java:27)
        at com.auth0.jwt.JWT.decode(JWT.java:45)
```

`tokenResult.getToken()` is from the Firebase SDK and returns a string.

**Comment by lbalmaceda** [comment]
@danielbaker this library is not meant for android. However, the one limiting issue I recall is this one. Android support for JDK8 is not available until later versions of it. So in order to provide proper coverage for older android versions, the `android.util.Base64` class should be used instead. Of course, that one cannot be referenced from this library. 

So far we've been recommending [this other library](https://github.com/auth0/JWTDecode.Android/) to decode (read: decode and not verify) a token on Android. I hope that helps.

**Comment by jimmyjames** [comment]
Change to `java.util.Base64` implemented in https://github.com/auth0/java-jwt/pull/401 - this will be included in Version 4.
