### ISSUE TITLE
Jwt's sign method , it need an option to remove tye JWT.

### ISSUE THREAD

**Issue by loveu8** [auth0/java-jwt#343]
Hi There, I am tring to use this lib to gen Sign in with Apple client_secret. But I find something different.
In this lib, Jwt's method sign always set tye 'JWT' , but in Apple's client_secret don't need it to exchange data. Would you consider this typ parameter can be removed? Thanks a lot.

---

```
public String sign(Algorithm algorithm) throws IllegalArgumentException, JWTCreationException {
            if (algorithm == null) {
                throw new IllegalArgumentException("The Algorithm cannot be null.");
            }
            headerClaims.put(PublicClaims.ALGORITHM, algorithm.getName());
            headerClaims.put(PublicClaims.TYPE, "JWT"); // <-- here
            String signingKeyId = algorithm.getSigningKeyId();
            if (signingKeyId != null) {
                withKeyId(signingKeyId);
            }
            return new JWTCreator(algorithm, headerClaims, payloadClaims).sign();
        }
```

---

Apple doc
https://developer.apple.com/documentation/signinwithapplerestapi/generate_and_validate_tokens

Apple jwt example
https://imgur.com/DwsruhC

----

Java jwt
https://imgur.com/JzysOdD

ruby jwt
https://imgur.com/bRungzO

**Comment by lbalmaceda** [comment]
@loveu8 the header claim `typ` is "JWT" because of the spec. https://tools.ietf.org/html/rfc7519#section-5.1. I just checked the implementation and despite what you pass on the header claims, `alg` and `typ` are always overwritten. I will research and may consider allowing the `typ` one to be customized. However again, this is part of the spec and I don't think there will be much room to customization. 
I don't know how apple works, but I suppose it would ignore the `typ` you send. Have you already tried that? And so, did you run into any errors you can share?
