### ISSUE TITLE
JWTVerifier with varargs is ambiguous

### ISSUE THREAD

**Issue by Jumwah** [auth0/java-jwt#344]
### Description

The methods `public Verification withIssuer(String... issuer)` and `public Verification withAudience(String... audience)` in `JWTVerifier` are designed to either remove a claim OR not set the claim if the passed argument is null.  

However, considering the parameters are varags it is very ambiguous when calling this, and at runtime, the actual result is often a list containing a null.  The result is that it considers this a valid claim, and the claim required is `null` which can never be satisfied.

This comes about specifically when using `com.auth0.spring.security.api.JwtAuthenticationProvider` in `auth0-spring-security-api` which builds a `JWTVerifier` always passing a `audience`.  I have no audience, but passing a null through here, is translated into a list of a single null value.

### Environment

`com.auth0:auth0-spring-security-api:1.2.3`
`com.auth0:java-jwt:3.8.1`

### Reproduction

Using the Spring security library above in the basic example of:
```        
JwtWebSecurityConfigurer
                .forHS256WithBase64Secret(null, config.issuer, config.secret)
                .configure(http)
                .headers().frameOptions().disable().and()
                .formLogin().disable()
                .cors().and().csrf().disable()
                .authorizeRequests()
                .anyRequest().permitAll()
```
demonstrates this bug. The key line is passing `null` as the first parameter to `forHS256WithBase64Secret`  A token containing no `aud` claim will be rejected with error `The Claim 'aud' value doesn't contain the required audience.`.  
Passing an empty string obviously also fails - which means there is no way I can use this library without an `aud`.  Regardless of ideals, for my use where we do not specify an audience in our JWTs, we cannot use this library.

**Comment by Jumwah** [comment]
@lbalmaceda

**Comment by lbalmaceda** [comment]
> Passing an empty string obviously also fails - which means there is no way I can use this library without an aud.

This issue should have been created on the `auth0-spring-security-api` SDK, not on this repo. Like the name of the library says, it's supposed to be used on a server side app that acts as an API. An audience will always be expected for you to set. Maybe the issue is that that library is not checking the presence of that required value. What is your use case that you have "no audience"?

> but passing a null through here, is translated into a list of a single null value.

Regarding this SDK's public API, the way it is supposed to work is if you pass `withAudience("my audience")` to the verifier builder you are implying that you expect a given audience value. If you pass null, that expectation (if one was set) should be removed. I'd expect that passing `withAudience(null)` removes the check. And that is being tested [here](https://github.com/auth0/java-jwt/blob/6ffa7032d26ebd69a16b9ed62bd8eef628aee133/lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java#L154-L162).

**Comment by jimmyjames** [comment]
Closing this issue here; any updates will be discussed in https://github.com/auth0/auth0-spring-security-api/issues/39
