### ISSUE TITLE
Issue trying to port from JavaScript into Java (Scala)

### ISSUE THREAD

**Issue by jrgleason** [auth0/java-jwt#433]
### Description

First I was referred to open this as an issue [here](https://community.auth0.com/t/need-help-converting-javascript-jwt-parsing-into-java-using-auth0-libs/47387), I realize this is more of a question...

I am having an issue converting some code from the JavaScript JWT library to the Java one.

### Reproduction

Currently I am using the node-jsonwebtoken lib you guys put out to parse my JWT access token. I do this like...

`jwt.verify(accessToken, cert, { algorithms : "RSA256" }).then((err, parsed) =>{...});`

I would like to do a similar thing in Java using java-jwt (well actually Scala but I don't see a Scala lib so using the Java one). But when I look at the docs it suggests I need the public key too (which I don't have and am not sure where to look for it). 

    val privateKey : RSAKey = ? // Not sure here but from cert var
    val algo: Algorithm  = Algorithm.RSA256(?, privateKey) // Or here
    val verifier = JWTVerifier.require(algo).build()
    verifier.verify(accessToken)

Can you provide a similar example for Java?

**Comment by lbalmaceda** [comment]
@jrgleason lets see if I can explain. 

On your JS snippet, you are using a `cert` variable, with the value of the public key certificate, I assume. If you are confident its value won't change ever, sure you can hardcode it in your code. 

The recommendation, however, is to pull it from the `{YOUR_DOMAIN}/.well-known/jwks.json` file. Auth0 generates a key pair for your tenant or account and uses the private key to sign the tokens. It also exposes the public key certificate in that URL I mentioned before. That way, when you decide to rotate the keys, you don't need to touch your app's code. That's the core benefit.

If you still want to hardcode it, you'd need to read that certificate into a `PublicKey` instance and feed that to the algorithm instance. A way to do it is as I explain on this gist [here](https://gist.github.com/lbalmaceda/9a0c7890c2965826c04119dcfb1a5469). You'd then instantiate the algorithm like

```java
PublicKey pub = //read key from file or raw string
Algorithm alg = Algorithm.RSA256(publicKey, null);
```
> I'm passing null for the private key because you're not going to do the signing.

Provided you want to use the JWKS approach, you'd need to pass a callback function on Algorithm instantiation. Since the public keys can rotate, each token includes a "kid" claim (key id) in the header that is associated to the public key that should be used to verify its signature. This library would extract that, and call your function with the _kid_ value. You must provide a PublicKey instance, just like before, but for the requested key id. How the code would look on this scenario is showed [here](https://github.com/auth0/java-jwt#using-a-keyprovider). At the end of that section, there's also our recommendation on a JWKS library that also works for Java and is able to pull the JWKS contents and construct a PublicKey instance for you. You only need to provide the URL.

Once you have your algorithm instance, all you need to do is call `JWT.require(algorithm)` and start writing your expectations. Build that object and call verify passing the string token. This is explained [here](https://github.com/auth0/java-jwt#verify-a-token).

**Comment by jrgleason** [comment]
Thank you I will try this out

**Comment by jimmyjames** [comment]
@jrgleason did you get a chance to try out @lbalmaceda's suggestion?

**Comment by jimmyjames** [comment]
Closing this issue; @jrgleason if you are still having this issue and provide more information about trying out the suggestion above, please let us know and we can reopen it.
