### ISSUE TITLE
Question: Is this library affected by commons-codec issue CODEC-279?

### ISSUE THREAD

**Issue by skjolber** [auth0/java-jwt#435]
### Description

We're worried that a bug / corner-case introduced via version 1.14 of the commons-codec library (via the latest Spring Boot 2.3) will affect us:

https://issues.apache.org/jira/browse/CODEC-279?

This library is already on 1.14, so can you confirm that tokens issued by Auth0 are not affected by this bug / corner-case?

### Reproduction

Given the understanding of Base64, the occational JWT token might not be decoded correctly.

### Environment

JVM / Spring Boot applications

**Comment by jimmyjames** [comment]
Looking at the details of [CODEC-279](https://issues.apache.org/jira/browse/CODEC-279), it appears this issue can happen with Base64 decoding when the input is either improperly encoded or truncated. I would _assume_ that would not be the case for any Auth0-issued tokens, but you can follow up with https://support.auth0.com for details regarding that. I did test the decoding with JDK11 and an Auth0-issued token and it was fine, but of course that's just with one specific JWT.

That said, the fix for the related issue ([CODEC-280](https://issues.apache.org/jira/browse/CODEC-280)) will be in 1.15, so when that is released we will upgrade that dependency here.

Does that help?

**Comment by skjolber** [comment]
No, it does not really help; don't know when 1.15 will be out? 

Can you share which library you're using to base-64-encode tokens in your service? If that is not confidential. The best way forward to is to look on the corner cases of that encoder, and perhaps also use it to encode a few million tokens (or just any random data really) and decoded using the commons-codec library to see if the bug manifests.

**Comment by jimmyjames** [comment]
I couldn't find when 1.15 of commons-codec will be released either. They seem to release about ~2 times per year, so I'd hope it won't be too long, but that's just a guess.

Regarding how the tokens are encoded, that's a question best directed to auth0.com/support.

I haven't tried it, but is it possible to override the commons-codec dependency down to 1.13 in your application, which from what I understand doesn't have this corner-case bug?

**Comment by skjolber** [comment]
Support did not provide a very detailed description, but to finish up I've written a [test bench](https://github.com/auth0/java-jwt/files/5155966/CODEC-279.zip):

Assumptions:
 * running node version 10, 12 or 14, with
 * native base64 encoder + search and replace for URL-safety

I've **not** been able to reproduce the problem, running millions of iterations.

**Comment by skjolber** [comment]
No longer worried, thanks for the help! :+1:
