### ISSUE TITLE
Multiple Audience Support

### ISSUE THREAD

**Issue by PvanHengel** [auth0/java-jwt#449]
Hello,

It seems there is a bug / issue / lack of feature with the audience validation logic.  If you pass a list of audiences, it must be in all of them, not just one.  I believe it's not "standard" to allow multiple audiences as is done with the Issuer claim.  

Please see the logic on line 415 
https://github.com/auth0/java-jwt/blob/dd6bc25d9a7c2857bae29757a9198b798ac5734f/lib/src/main/java/com/auth0/jwt/JWTVerifier.java#L415

vs the logic on line 421
https://github.com/auth0/java-jwt/blob/dd6bc25d9a7c2857bae29757a9198b798ac5734f/lib/src/main/java/com/auth0/jwt/JWTVerifier.java#L421

Would it be possible to give us the option to validate all or at least one?  Its unclear to me why we have a list for aud, and a single value for issuer, but thats neither here nor there, can we simply check if one exists?  Not sure if this would need a broader vetting, or perhaps a new api to check for at least one vs all?

Could we simply tweak like 415 with **Collections.disjoint(audience, value);** instead of **!audience.containsAll(value);**

**Comment by jimmyjames** [comment]
When validating a JWT, you can specify the audience(s), and the expectation is that all of the expected audiences are contained in the JWT's `aud` claim. The JWT may contain additional audiences than those specified to validate, but it must contain all the audiences specified.

For example, consider a JWT with an `aud` claim value of `[https://domain.auth0.com/userinfo, https://api-id.com]`. When validating the JWT, you can pass `[https://domain.auth0.com/userinfo]` to ensure the token is valid for the userinfo API, or `[https://api-id.com]` to ensure the token is valid for some custom API, or pass both to ensure the token is valid to be used for both APIs.

**Comment by PvanHengel** [comment]
@jimmyjames  Agreed that is how it works today, but in our use case we do not want to require that they all are there, rather we want to require that at least one of the list is there.  We did work around this by doing a multiple pass validation logic but it seems a little ugly.

**Comment by jimmyjames** [comment]
@PvanHengel when you say you do a multiple pass validation as a workaround, do you mean you are running multiple verifications until one passes with one of the expected audiences?

It might be cleaner to just skip audience validation in this scenario, and instead validate your expectations from the decoded JWT claim.

Regarding updating the SDK to support validating at least one of the expected audience is present, instead of all of them, I think it's something we should do. I don't know if it's something we can do really soon, as changing the current behavior would be a breaking change, so would need to be done in the next major release. Perhaps there's a non-breaking way to enable this functionality, and if so we can do that.

**Comment by jimmyjames** [comment]
@PvanHengel does the changes in #472 look like they will meet your requirements?
