### ISSUE TITLE
token is still alive, when "exp" = NOW

### ISSUE THREAD

**Issue by taisuke-fujimoto** [auth0/java-jwt#646]
### Describe the problem
I tried with the code below, but no exception occurred. (TokenExpiredException occurs when `Clock` is +1 second)
This means that token lifetime is `NOW <= "exp"`
```kotlin
// kotlin code
val expiresAt = Instant.now()
val token = JWT.create()
    .withExpiresAt(expiresAt)
    .sign(Algorithm.HMAC256("test"))

val verifier = (JWT.require(Algorithm.HMAC256("test")) as JWTVerifier.BaseVerification)
    .build(Clock.fixed(expiresAt, ZoneId.of("UTC")))

verifier.verify(token)
```

Shouldn't the token lifetime be `NOW < "exp"`?

I think this description is correct.
https://github.com/auth0/java-jwt/blob/master/EXAMPLES.md#datetime-claim-validation

### Environment
- **Version of this library used:** 4.2.1
- **Version of Java used:** 11
- **Other modules/plugins/libraries that might be involved:** Kotlin 1.7.22

**Comment by jimmyjames** [comment]
Hey @taisuke-fujimoto, thanks for the issue and test case. Yes, the specification states that the `exp` must be before the current time, so it looks like there is an off-by-1 second here.

**Comment by justeff** [comment]
The problem is in the **assertInstantIsFuture** method.

The mentioned description in the examples says a token is valid if exp > NOW. The specification says, a token should be rejected if exp < NOW (**on or after**). Both statements are not equal as with exp > NOW we would even allow exp = NOW.

In **assertInstantIsFuture** the following statement is being used to check for a valid token:
!now.isAfter(exp) or !(NOW > exp) or NOW < exp or exp > NOW

But it should be:
!(exp < NOW) or !(exp.isBefore(now))

**Comment by justeff** [comment]
The problem is in the **assertInstantIsFuture** method.

The specification states:
_The "exp" (expiration time) claim identifies the expiration time **on or after** which the JWT MUST NOT be accepted for processing.  The processing of the "exp" claim requires that the current date/time MUST be **before** the expiration date/time listed in the "exp" claim._

That means:
- A token isn't expired and valid if NOW < exp or exp > NOW (fits with the mentioned description in the example)
- A token is expired if NOW >= exp or exp <= NOW

The method _assertInstantIsFuture_ checks for a valid token with:
!now.isAfter(exp) -> !(NOW > exp)

But the correct ways would be:
- NOW < exp -> now.isBefore(exp) or
- exp > NOW -> exp.isAfter(now)
