### ISSUE TITLE
Add Support for the EdDSA Signatures

### ISSUE THREAD

**Issue by dylanjrae** [auth0/java-jwt#654]
### Describe the problem you'd like to have solved

Requesting support for using Ed25519 keys for encoding/decoding JWT's. We can't find any Java JWT library that supports these signatures, see: https://jwt.io/libraries?language=Java

### Describe the ideal solution

Integrated EdDSA support as with others such as RS256.

## Alternatives and current work-arounds
Unaware of any alternative java jwt libaries that support EdDSA

### Additional information, if any
Have seen a couple others requesting this feature, it is faster and uses shorter keys than other alternatives. Perhaps [this](https://github.com/str4d/ed25519-java) resource could be of assistance?

**Comment by jimmyjames** [comment]
hey @dylanjrae, I'm not super familiar with Ed25519 on Java, but I think java support for it might be something added to Java 15+? If we were to support this algorithm, we'd need to do it in a way that doesn't require a Java runtime beyond 8, at least for v4, to ensure compatibility. If it's possible in a non-breaking way we can consider it, though it's not likely to be a high priority for us in the short term.

**Comment by jimmyjames** [comment]
This is something we'll consider adding support for in v5, when I imagine we'll require Java 17+ as a baseline requirement.

**Comment by leonard84** [comment]
@jimmyjame, are there any plans for when v5 will be released? It has been two years since then, and competitor libraries support it even while staying on a Java 8 baseline. They treat the algorithm as optional and will enable it on JDK 15+ or if Bouncy Castle is on the classpath.

- https://connect2id.com/products/nimbus-jose-jwt/examples/jws-with-eddsa
- https://github.com/jwtk/jjwt/blob/master/impl/src/main/java/io/jsonwebtoken/impl/security/EdSignatureAlgorithm.java
- https://github.com/jwtk/jjwt/blob/master/impl/src/main/java/io/jsonwebtoken/impl/security/EdwardsCurve.java
